### ISSUE TITLE
manual firebase

### ISSUE THREAD

**Issue by phsilvasantos** [alt-zap/alt-zap#51]
poderia fazer um paso a passo do frebase

**Comment by lucis** [comment]
@phsilvasantos vou fazer sim! Na verdade a próxima release (que tá no PR aberto) já adiciona um emulador do Firebase para facilitar o desenvolvimento local. Assim que lançar aviso aqui

**Comment by phsilvasantos** [comment]
obrigado pleo retorno

**Comment by lucis** [comment]
Fechado com #44
