### ISSUE TITLE
Adicionar restante das categorias de Tenant

### ISSUE THREAD

**Issue by lucis** [alt-zap/alt-zap#71]
![image](https://user-images.githubusercontent.com/18706156/94874837-75b68c00-0429-11eb-90f6-27ff6d4d6a42.png)

**Comment by ItaloSa** [comment]
Poderia dar mais detalhes?

**Comment by lucis** [comment]
@ItaloSa seria, basicamente, melhorar essa categorização aí adicionando outras opções. 

Também acredito que hoje em dia esteja hard-coded os nomes desse jeito (`"Pizzaria"`), o que é ruim pra internacionalização, então seriam duas coisas:
- Mudar para utilizar apenas algumas chaves (ex:  `pizza`) e fazer a tradução na UI utilizando `useAltIntl()` (ver: `intlConfig.ts` ou procurar por `useAltIntl()`).
- Adicionar outras opções de estabelecimento.
