### ISSUE TITLE
Possibilidade de variações dos produtos

### ISSUE THREAD

**Issue by rerissondaniel** [alt-zap/alt-zap#95]
É possível adicionar variações para os produtos? Ex.: Tamanho para pizzas?

**Comment by lucis** [comment]
Quase, @rerissondaniel!

Há um tempo fiz todo o arcabouço para isso (a parte do Admin que era a mais complicada) e parei para dar prioridade a outras coisas, mas estou trabalhando nisso atualmente [nessa branch](https://github.com/alt-zap/alt-zap/tree/feature/order-with-assemblies).

Espero lançar logo (1 ou 2 semanas), liberando a parte no admin (atualmente eu escondi com um `false && <Component...`) e também a parte da página de pedidos.

É um pouco demorado pois a configuração é bem genérica e preciso criar as coisas com cuidado.

**Comment by lucis** [comment]
@rerissondaniel feature lançada.

Dá pra ver como usa [aqui](https://docs.alt.app.br/docs/guides/configurando-opcoes-de-montagem-de-produto).

**Comment by rerissondaniel** [comment]
Show demais! Indiquei pra uma pizzaria daqui
