### ISSUE TITLE
Possibilidade de adicionar produto combo

### ISSUE THREAD

**Issue by socketlab** [alt-zap/alt-zap#98]
Alguma possibilidade de ter adicionais, opcionais ou complementos de um produto?

**Comment by lucis** [comment]
@socketlab sim, deve sair essa semana! Tecnicamente, será a mesma funcionalidade que comentei no #95.

A configuração permitida será bem vasta:

![image](https://user-images.githubusercontent.com/18706156/97819260-2d87c500-1c86-11eb-86cf-13700fdef70a.png)

Estou agora escrevendo alguns tutoriais para liberar a funcionalidade já com o devido material.

**Comment by socketlab** [comment]
top

**Comment by lucis** [comment]
@socketlab  feature lançada.

Dá pra ver como usa [aqui](https://docs.alt.app.br/docs/guides/configurando-opcoes-de-montagem-de-produto).
